name: CI

on:
  push:
    branches:
      - main
      - integrate-ci

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
    
      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: npx eslint . --max-warnings=0

      - name: Secret scan
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
